# RegEx Patterns generated by ChatGPT for electronic music
from config import get_regex_patterns_config

regex_patterns = get_regex_patterns_config()

if __name__ == "__main__":
    print(regex_patterns)
