# RegEx Patterns generated by ChatGPT for electronic music
regex_patterns = {
    "house": [
        "\\bdeep\\s+house\\b",
        "\\btech\\s+house\\b",
        "\\bprogressive\\s+house\\b",
        "\\btropical\\s+house\\b",
        "\\bfuture\\s+house\\b",
        "\\bacid\\s+house\\b",
        "\\belectro\\s+house\\b"
    ],
    "techno": [
        "\\bminimal\\s+techno\\b",
        "\\bdetroit\\s+techno\\b",
        "\\bacid\\s+techno\\b",
        "\\bindustrial\\s+techno\\b",
        "\\bhard\\s+techno\\b",
        "\\btech\\s+techno\\b"
    ],
    "trance": [
        "\\bprogressive\\s+trance\\b",
        "\\buplifting\\s+trance\\b",
        "\\bpsychedelic\\s+trance\\b",
        "\\bgoa\\s+trance\\b",
        "\\btech\\s+trance\\b",
        "\\bvocal\\s+trance\\b"
    ],
    "dubstep": [
        "\\bbrostep\\b",
        "\\bchillstep\\b",
        "\\briddim\\b",
        "\\bdeep\\s+dubstep\\b"
    ],
    "drum_and_bass": [
        "\\bdnb\\b",
        "\\bneurofunk\\b",
        "\\bliquid\\s+funk\\b",
        "\\bjump\\s+up\\b",
        "\\bdarkstep\\b",
        "\\bbreakcore\\b"
    ],
    "electro": [
        "\\belectro\\b",
        "\\belectro\\s+funk\\b",
        "\\belectro\\s+clash\\b",
        "\\bfuture\\s+electro\\b"
    ],
    "hardcore": [
        "\\bhardcore\\b",
        "\\bgabber\\b",
        "\\bhappy\\s+hardcore\\b",
        "\\bdigital\\s+hardcore\\b",
        "\\bbreakbeat\\s+hardcore\\b"
    ]
}